# Generated by Django 4.1 on 2024-04-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('gender', models.BooleanField()),
                ('dob', models.DateField()),
                ('POB', models.CharField(max_length=100, null=True)),
                ('Nationality', models.CharField(max_length=100, null=True)),
                ('body_marks', models.CharField(max_length=100, null=True)),
                ('gang', models.CharField(max_length=100, null=True)),
                ('wantedby', models.CharField(max_length=100)),
                ('ctype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Arrests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.profile')),
            ],
        ),
    ]
