# Generated by Django 4.1 on 2024-05-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wantedby', models.CharField(max_length=100)),
                ('ctype', models.CharField(max_length=100)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Arrests',
        ),
    ]
